### ISSUE TITLE
Support Windows machine in Github Action Workflows

### ISSUE THREAD

**Issue by tangxifan** [os-fpga/FOEDAG#14]
**Is your feature request related to a problem? Please describe.**
Windows is a popular platform where most GUI projects are run.
It is reasonable to ensure that our GUI is continuously deliverable on Windows platform

**Describe the solution you'd like**
Set up a workflow on Github Actions, testing
- Build compatibility of the codes on Windows machines
- Run regression tests on Windowns machines

Refer to the workflow example at 

https://github.com/chipsalliance/Surelog/blob/ac38329a10128579831ee8fd8dfa7a8bcfbfb936/.github/workflows/main.yml#L128

**Comment by alain-rs** [comment]
MSVC is supported.
TODO: MSYS2

**Comment by umarcor** [comment]
As a rule of thumb, using the MSYS environment of MSYS2 is discouraged, because that produces windows binaries that depend on the abstraction DLL. Conversely, by using MINGW64, UCRT64, etc. binaries can be standalone.

At the same time, inherting the PATH can produce conflicts because GitHub's virtual environments do have a default msys2 installation added to it. If possible, it is recommend to use the default isolation.

**Comment by alaindargelas** [comment]
@umarcor, I'd gladly pass you the torch to finish this task of getting the compilation and tests running in the CI!
I'm shooting in the dark and making slow progress here. I'm a Windows beginner (After 30 years on Linux....).

**Comment by alaindargelas** [comment]
If you can, also review the MSVC port I did.

**Comment by umarcor** [comment]
@alaindargelas, unfortunately I'm off my limit with regard to maintaining EDA packages/tools on MSYS2 (https://hdl.github.io/MINGW-packages/#_packagestools), and I cannot take care of CI in more repos. Creating PKGBUILD recipes for Verible, Surelog and UHDM is in my scope (that might be used as a foundation here), but not prioritary at the moment.

Nevertheless, if you are a Linux user, you might feel more comfortable writting a PKGBUILD recipe for FOEDAG, rather than trying to write a GitHub Actions workflow step by step. PKGBUILD recipes are based on the tooling from Arch Linux (makepkg, pacman, etc.). You can find an example workflow and recipe in https://github.com/msys2/setup-msys2/tree/master/examples#pkgbuild.

**Comment by tangxifan** [comment]
@alain-rs I have installed msys2 on my windows machine and used pacman to install Qt5.
Here is the path to Qt5 cmake files

```
C:\msys64\mingw64\lib\cmake\Qt5\Qt5Config.cmake
```

In msys2 shell, you may try

```
/mingw64/lib/cmake/Qt5/Qt5/Qt5Config.cmake
``

**Comment by alaindargelas** [comment]
@tangxifan, OK, QT install done and recognized,
now the next error is happening during the Tcl config step.
We need to run that locally in msys to understand

**Comment by alain-rs** [comment]
- Windows MSVC is fully supported.
- Msys2 compiles but does not link, undefined references to Microsoft basic Windows library symbols. Compilation is on but linkage and tests are off in the Action.
