### ISSUE TITLE
add_design_file/add_constraint creates new file if it doesn't exists

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#476]
**Describe the bug**
add design file from the GUI console creates file if it doesn't exist.

**To Reproduce**
* Open FOEDAG
* run the console:
** create_design asd
** add_design_file asd.v

**Expected behavior**
Command should show error if file doesn't exists. No new created file.

checked commit: 3329563789d190f03163091eb61b984445e35463

**Comment by alain-rs** [comment]
No it should not.
Project folder is Foedag specific. Design files are part of the Design. The Design can be run outside Foedag by other tools (Simulators....).

**Comment by KochynVolodymyr** [comment]
I'm not agree, it is not logically. When we create new design at the same time we create folder structure for this design. It is more logically that new created file appears inside this folder.

**Comment by KochynVolodymyr** [comment]
@alain-rs  here is some misunderstanding. Command **add_design_file** creates new file if it doesn't exists. And new file is created outside the project folder. So, is this correct behavior? If yes, I'll close this bug.

**Comment by alaindargelas** [comment]
I thing the problem is here:
In 99% of the case, the design already exists and has been created by the user. They used vi, emacs, whatever editor and the design already is running in another tool (Simulator, competitive synthesis tool).
Only in 1%, the user will use Foedag to create the design.

So all the design definition commands are really "import" commands. add_design_file is adding a file to the project, it is not supposed to create a file. It is actually supposed to error out if the file does not exist.

What you mean is "create_design_file" command that does not exist yet. From the GUI, you should distinguish adding and creating.

**Comment by KochynVolodymyr** [comment]
Got it!
